name: in_my_bush
description: "In my bush — marketplace de produits bio (Madagascar). Application mobile acheteur + vendeur."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.0.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.15.1
  json_serializable: ^6.14.1

flutter:
  uses-material-design: true
